CRITICAL - 2022-06-08 09:24:01 --> Invalid file: nuevoEmpleado.php
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('nuevoEmpleado.p...')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('nuevoEmpleado', Array, true)
#2 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(108): view('nuevoEmpleado', Array)
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-06-08 09:25:52 --> Invalid file: empleado/1.php
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('empleado/1.php')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/1', Array, true)
#2 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(108): view('empleado/1')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-06-08 09:26:12 --> Invalid file: empleados/1.php
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('empleados/1.php')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleados/1', Array, true)
#2 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(108): view('empleados/1')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-06-08 10:33:59 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;apv_tributable&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...ivil&quot;, &quot;discapacidad&quot;, &quot;foto&quot;, &quot;afp&quot;, &quot;apv_tipo&quot;, &quot;apv_tribu...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 10:33:59 --> pg_query(): Query failed: ERROR:  column &quot;apv_tributable&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...ivil&quot;, &quot;discapacidad&quot;, &quot;foto&quot;, &quot;afp&quot;, &quot;apv_tipo&quot;, &quot;apv_tribu...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 10:38:22 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 10:38:22 --> pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 10:44:35 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 10:44:35 --> pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 10:45:31 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 10:45:31 --> pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 10:55:25 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 10:55:25 --> pg_query(): Query failed: ERROR:  column &quot;seguro_censatia_2002&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...rgas_invalidez&quot;, &quot;cargas_maternales&quot;, &quot;jubilado&quot;, &quot;seguro_ce...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 11:01:53 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;trabajo_pesajo_porcentaje&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...solidario&quot;, &quot;seguro_invalidez&quot;, &quot;trabajo_pesado&quot;, &quot;trabajo_p...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 11:01:53 --> pg_query(): Query failed: ERROR:  column &quot;trabajo_pesajo_porcentaje&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...solidario&quot;, &quot;seguro_invalidez&quot;, &quot;trabajo_pesado&quot;, &quot;trabajo_p...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 11:03:16 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;cuenta2&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...&quot;, &quot;trabajo_pesado&quot;, &quot;trabajo_pesado_porcentaje&quot;, &quot;cuenta2&quot;,...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 11:03:16 --> pg_query(): Query failed: ERROR:  column &quot;cuenta2&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...&quot;, &quot;trabajo_pesado&quot;, &quot;trabajo_pesado_porcentaje&quot;, &quot;cuenta2&quot;,...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(104): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-08 11:11:56 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;cuenta2_tipo&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...&quot;, &quot;trabajo_pesado&quot;, &quot;trabajo_pesado_porcentaje&quot;, &quot;cuenta2_t...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(103): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 11:11:56 --> pg_query(): Query failed: ERROR:  column &quot;cuenta2_tipo&quot; of relation &quot;empleados&quot; does not exist
LINE 1: ...&quot;, &quot;trabajo_pesado&quot;, &quot;trabajo_pesado_porcentaje&quot;, &quot;cuenta2_t...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #140, 'INSERT INTO "em...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "em...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "em...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "em...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(103): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-08 11:28:50 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(105): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-06-08 11:33:31 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(105): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-06-08 11:35:09 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(105): CodeIgniter\HTTP\RedirectResponse->route(false, Array)
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->add()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-06-08 11:44:37 --> Undefined variable: empresaModel
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('3')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-08 12:42:16 --> Too few arguments to function App\Controllers\EmpleadoController::update(), 0 passed in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php on line 832 and exactly 1 expected
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update()
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-08 12:46:20 --> Undefined variable: empresaModel
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(169): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 169, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-08 12:46:27 --> Undefined variable: empresaModel
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(169): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 169, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-08 12:47:48 --> Call to undefined function App\Controllers\EmpleadoModel()
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-08 12:49:21 --> Call to undefined method CodeIgniter\HTTP\RedirectResponse::withErrors()
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-06-08 12:50:20 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for integer: &quot;11.111.111-1&quot;
LINE 1: ... &quot;id_empresa&quot; = '1', &quot;nombres&quot; = 'Cesar', &quot;rut&quot; = '11.111.11...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #144, 'UPDATE "emplead...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "emplead...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "emplead...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "emplead...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(170): CodeIgniter\Model->update('3', Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-06-08 12:50:20 --> pg_query(): Query failed: ERROR:  invalid input syntax for integer: &quot;11.111.111-1&quot;
LINE 1: ... &quot;id_empresa&quot; = '1', &quot;nombres&quot; = 'Cesar', &quot;rut&quot; = '11.111.11...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #144, 'UPDATE "emplead...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "emplead...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "emplead...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "emplead...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(170): CodeIgniter\Model->update('3', Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-08 12:51:15 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for integer: &quot;11.111.111-1&quot;
LINE 1: ... &quot;id_empresa&quot; = '1', &quot;nombres&quot; = 'Cesar', &quot;rut&quot; = '11.111.11...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #144, 'UPDATE "emplead...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "emplead...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "emplead...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "emplead...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(170): CodeIgniter\Model->update('3', Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-06-08 12:51:15 --> pg_query(): Query failed: ERROR:  invalid input syntax for integer: &quot;11.111.111-1&quot;
LINE 1: ... &quot;id_empresa&quot; = '1', &quot;nombres&quot; = 'Cesar', &quot;rut&quot; = '11.111.11...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #144, 'UPDATE "emplead...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "emplead...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "emplead...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "emplead...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(170): CodeIgniter\Model->update('3', Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-06-08 12:51:37 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for integer: &quot;11.111.111-1&quot;
LINE 1: ... &quot;id_empresa&quot; = '1', &quot;nombres&quot; = 'Cesar', &quot;rut&quot; = '11.111.11...
                                                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #144, 'UPDATE "emplead...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "emplead...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "emplead...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "emplead...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(170): CodeIgniter\Model->update('3', Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-06-08 12:51:37 --> pg_query(): Query failed: ERROR:  invalid input syntax for integer: &quot;11.111.111-1&quot;
LINE 1: ... &quot;id_empresa&quot; = '1', &quot;nombres&quot; = 'Cesar', &quot;rut&quot; = '11.111.11...
                                                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #144, 'UPDATE "emplead...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "emplead...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "emplead...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE "emplead...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#8 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(170): CodeIgniter\Model->update('3', Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-06-08 13:59:47 --> syntax error, unexpected '}', expecting ';'
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(797): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-08 14:00:23 --> Undefined variable: validation
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(173): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 173, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->update('3')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-08 14:25:46 --> Call to undefined function errors()
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/editar', Array, true)
#3 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(27): view('empleado/editar', Array)
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('3')
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-08 14:28:51 --> Array to string conversion
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\editar.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/editar', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(27): view('empleado/editar', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('3')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-08 14:32:09 --> Call to undefined function issetvar_dump()
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include()
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/editar', Array, true)
#3 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(27): view('empleado/editar', Array)
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('3')
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-08 14:59:46 --> Use of undefined constant selected - assumed 'selected' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\editar.php(102): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 102, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/editar', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(27): view('empleado/editar', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('3')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-08 14:59:49 --> Use of undefined constant selected - assumed 'selected' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\editar.php(102): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 102, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/editar', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(27): view('empleado/editar', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('3')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-06-08 15:38:41 --> ErrorException: pg_query(): Query failed: ERROR:  syntax error at or near "0"
LINE 1: INSERT INTO "afp_tipos" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1...
                                 ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #163, 'INSERT INTO "af...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "af...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "af...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "af...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Seeds\AfpTipos.php(80): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\AfpTipos->run()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'AfpTipos')
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-06-08 15:46:43 --> ErrorException: pg_query(): Query failed: ERROR:  syntax error at or near "0"
LINE 1: INSERT INTO "afp_tipos" (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1...
                                 ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #163, 'INSERT INTO "af...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "af...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "af...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "af...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Seeds\AfpTipos.php(80): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Seeder.php(147): App\Database\Seeds\AfpTipos->run()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'AfpTipos')
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2022-06-08 16:48:56 --> syntax error, unexpected ')'
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(797): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-08 18:01:10 --> Undefined variable: empleado
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\nuevo.php(114): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 114, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/nuevo', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(38): view('empleado/nuevo', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->create('1')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-08 18:01:33 --> Undefined variable: tipos_afp
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\nuevo.php(115): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 115, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/nuevo', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(38): view('empleado/nuevo', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->create('1')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
