CRITICAL - 2022-06-03 08:14:48 --> Undefined variable: empresa_id
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpresaController.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpresaController->add()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpresaController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2022-06-03 08:24:14 --> ErrorException: pg_query(): Query failed: ERROR:  insert or update on table &quot;users_empresas&quot; violates foreign key constraint &quot;users_empresas_fk_user_id&quot;
DETAIL:  Key (user_id)=(6) is not present in table &quot;users&quot;. in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #145, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Models\EmpresaModel.php(36): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpresaController.php(38): App\Models\EmpresaModel->asignarEmpresa(6)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpresaController->add()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpresaController))
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-03 08:24:14 --> pg_query(): Query failed: ERROR:  insert or update on table &quot;users_empresas&quot; violates foreign key constraint &quot;users_empresas_fk_user_id&quot;
DETAIL:  Key (user_id)=(6) is not present in table &quot;users&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #145, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Models\EmpresaModel.php(36): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpresaController.php(38): App\Models\EmpresaModel->asignarEmpresa(6)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpresaController->add()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpresaController))
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-03 08:26:58 --> Trying to get property 'resultID' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Models\EmpresaModel.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpresaController.php(38): App\Models\EmpresaModel->asignarEmpresa(7)
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpresaController->add()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpresaController))
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-06-03 08:27:12 --> Trying to get property 'resultID' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Models\EmpresaModel.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpresaController.php(38): App\Models\EmpresaModel->asignarEmpresa(8)
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpresaController->add()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpresaController))
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-06-03 11:50:53 --> Class 'App\Controllers\EmpresaModel' not found
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-06-03 14:58:13 --> ErrorException: pg_query(): Query failed: ERROR:  syntax error at or near "1"
LINE 27: ...d_empresa_foreign" FOREIGN KEY ("id_empresa") REFERENCES 1()
                                                                     ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'contratos')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:03:21 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:04:13 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:05:16 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleadps')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:05:51 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'contratos')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:05:59 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:20:11 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'App\\Database\\Mi...')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:21:09 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'App\\Database\\Mi...')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:21:30 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(135): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:27:23 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(139): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:28:20 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empresas" already exists in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "e...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "e...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "e...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "e...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-144337_empresas.php(122): CodeIgniter\Database\Forge->createTable('empresas')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Empresas->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:34:31 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empresas" already exists in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "e...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "e...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "e...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "e...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-144337_empresas.php(122): CodeIgniter\Database\Forge->createTable('empresas')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Empresas->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:34:59 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #164, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(139): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 15:48:47 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(139): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 16:01:15 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(139): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'contratos')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 16:01:40 --> ErrorException: pg_query(): Query failed: ERROR:  relation "empleados" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "c...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "c...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "c...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "c...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-151809_contratos.php(139): CodeIgniter\Database\Forge->createTable('contratos')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Contratos->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 16:06:14 --> ErrorException: pg_query(): Query failed: ERROR:  relation "users" does not exist in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "u...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "u...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "u...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "u...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-06-02-212121_EmpresasUsers.php(32): CodeIgniter\Database\Forge->createTable('users_empresas')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\EmpresasUsers->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 16:07:55 --> ErrorException: pg_query(): Query failed: ERROR:  date/time value "current" is no longer supported in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "u...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "u...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "u...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "u...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-114420_Users.php(44): CodeIgniter\Database\Forge->createTable('users')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Users->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 16:12:53 --> ErrorException: pg_query(): Query failed: ERROR:  date/time value "current" is no longer supported in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "u...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "u...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "u...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "u...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-114420_Users.php(44): CodeIgniter\Database\Forge->createTable('users')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Users->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-06-03 16:13:17 --> ErrorException: pg_query(): Query failed: ERROR:  date/time value "current" is no longer supported in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #166, 'CREATE TABLE "u...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "u...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "u...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Forge.php(513): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "u...')
#5 C:\xampp\htdocs\plataforma-contabilidad\app\Database\Migrations\2022-05-02-114420_Users.php(44): CodeIgniter\Database\Forge->createTable('users')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(863): App\Database\Migrations\Users->up()
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(186): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(70): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(56): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(830): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate', 'empleados')
#13 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\plataforma-contabilidad\spark(63): CodeIgniter\CLI\Console->run()
#17 {main}
CRITICAL - 2022-06-03 16:17:11 --> Trying to get property 'nombre' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\listar.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/listar', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(14): view('empleado/listar', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-06-03 16:17:46 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;name&quot; of relation &quot;users&quot; does not exist
LINE 1: INSERT INTO &quot;users&quot; (&quot;name&quot;, &quot;email&quot;, &quot;password&quot;) VALUES ('M...
                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\RegistroController.php(32): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\RegistroController->store()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegistroController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-03 16:17:46 --> pg_query(): Query failed: ERROR:  column &quot;name&quot; of relation &quot;users&quot; does not exist
LINE 1: INSERT INTO &quot;users&quot; (&quot;name&quot;, &quot;email&quot;, &quot;password&quot;) VALUES ('M...
                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\RegistroController.php(32): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\RegistroController->store()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegistroController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-03 16:18:47 --> ErrorException: pg_query(): Query failed: ERROR:  null value in column &quot;nombre&quot; violates not-null constraint
DETAIL:  Failing row contains (1, null, jmunoz@gpscontrol.cl, $2y$10$DUpM9WBeVB0OsmK6lH.dtuFwIEl6yxMjO0JoWX6EGoP9iW0xkcrYG, null, 2022-06-03 16:07:41.941058). in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\RegistroController.php(32): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\RegistroController->store()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegistroController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-03 16:18:47 --> pg_query(): Query failed: ERROR:  null value in column &quot;nombre&quot; violates not-null constraint
DETAIL:  Failing row contains (1, null, jmunoz@gpscontrol.cl, $2y$10$DUpM9WBeVB0OsmK6lH.dtuFwIEl6yxMjO0JoWX6EGoP9iW0xkcrYG, null, 2022-06-03 16:07:41.941058).
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\RegistroController.php(32): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\RegistroController->store()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegistroController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
ERROR - 2022-06-03 16:20:29 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;name&quot; of relation &quot;users&quot; does not exist
LINE 1: INSERT INTO &quot;users&quot; (&quot;name&quot;, &quot;email&quot;, &quot;password&quot;) VALUES ('M...
                             ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\RegistroController.php(32): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\RegistroController->store()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegistroController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-03 16:20:29 --> pg_query(): Query failed: ERROR:  column &quot;name&quot; of relation &quot;users&quot; does not exist
LINE 1: INSERT INTO &quot;users&quot; (&quot;name&quot;, &quot;email&quot;, &quot;password&quot;) VALUES ('M...
                             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #141, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\RegistroController.php(32): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\RegistroController->store()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RegistroController))
#12 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2022-06-03 17:03:45 --> Undefined variable: empeladoModel
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:04:07 --> Undefined variable: empleadoModel
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:04:33 --> Class 'App\Controllers\EmplesaModel' not found
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-06-03 17:05:48 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;empresa_id&quot; does not exist
LINE 3: WHERE &quot;empresa_id&quot; = '1'
              ^ in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #134, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(728): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(17): CodeIgniter\Model->__call('get', Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-03 17:05:48 --> pg_query(): Query failed: ERROR:  column &quot;empresa_id&quot; does not exist
LINE 3: WHERE &quot;empresa_id&quot; = '1'
              ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\Postgre\Connection.php(135): pg_query(Resource id #134, 'SELECT *\nFROM "...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Model.php(728): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(17): CodeIgniter\Model->__call('get', Array)
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->listAll('1')
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-06-03 17:43:51 --> Too few arguments to function App\Controllers\EmpleadoController::form(), 0 passed in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php on line 832 and exactly 1 expected
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-03 17:44:23 --> syntax error, unexpected ')'
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(797): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-06-03 17:44:30 --> Undefined variable: empresa
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\nuevo.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/nuevo', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(22): view('empleado/nuevo')
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form('3')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-03 17:45:13 --> Trying to get property 'nombre' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\nuevo.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/nuevo', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(25): view('empleado/nuevo', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form('3')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-03 17:45:14 --> Trying to get property 'nombre' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Views\empleado\nuevo.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('empleado/nuevo', Array, true)
#4 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(25): view('empleado/nuevo', Array)
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form('3')
#6 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#7 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-06-03 17:47:52 --> Call to undefined method App\Entities\Empleado::get()
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form('3')
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-03 17:50:14 --> Too few arguments to function App\Controllers\EmpleadoController::form(), 0 passed in C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php on line 832 and exactly 1 expected
#0 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-06-03 17:50:29 --> Trying to get property 'id_empresa' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:50:30 --> Trying to get property 'id_empresa' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:50:31 --> Trying to get property 'id_empresa' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:50:31 --> Trying to get property 'id_empresa' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:50:31 --> Trying to get property 'id_empresa' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->form()
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-06-03 17:51:08 --> Trying to get property 'id_empresa' of non-object
#0 C:\xampp\htdocs\plataforma-contabilidad\app\Controllers\EmpleadoController.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\EmpleadoController->edit('1')
#2 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EmpleadoController))
#3 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\plataforma-contabilidad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\plataforma-contabilidad\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
